### ISSUE TITLE
Suggestion: Make the placeholder clear (or with configurable background color)

### ISSUE THREAD

**Issue by tkafka** [globulus/swiftui-pull-to-refresh#10]
I have an image (gradient) in the background of my app, and pull-to-refresh created a solid color block overlaying it.

I fixed this by replacing `foregroundColor(Color(UIColor.systemBackground))` for `foregroundColor(Color.clear)` at https://github.com/globulus/swiftui-pull-to-refresh/blob/main/Sources/SwiftUIPullToRefresh/SwiftUIPullToRefresh.swift#L108 but I had to fork the project to do this.

It would be great if this could be configurable in a same way `progress` is (or, maybe just use the clear color as default?).

Thank you for consideration!

**Comment by gordan-glavas-codecons** [comment]
Hi Tomáš,

I added this via `loadingViewBackgroundColor` in v.1.1.4.

Thanks again for the suggestion!

**Comment by tkafka** [comment]
@gordan-glavas-codecons Awesome! Thank you very much!
