### ISSUE TITLE
Issue on haptic feedback

### ISSUE THREAD

**Issue by dev-lcc** [globulus/swiftui-pull-to-refresh#17]
Actual:
- User started to pull down the content view
- User reached the threshold height
  - Notification Success Haptic Feedback(https://developer.apple.com/design/human-interface-guidelines/patterns/playing-haptics/images/success.mp4) is dispatched
- Upon release, no haptic feedback.

Suggested:
- User started to pull down the content view
- User reached the threshold height, no haptic feedback.
- Upon release, dispatch Impact Light Haptic Feedback(https://developer.apple.com/design/human-interface-guidelines/patterns/playing-haptics/images/impact_light.mp4).

I think the suggested implementation is more natural than the current ones.

The current haptic feedback implementation best applies IF refresh action is immediately triggered upon reaching threshold height, rather than on release.
- example: When using Safari Browser, perform `pull down refresh`. Upon reaching threshold, it immediately reloads the page along with Impact Light haptic feedback

**Comment by gordan-glavas-codecons** [comment]
The PR is merged and will be release in v1.1.7.
