### ISSUE TITLE
`Conversion to Swift 5 is available` warning

### ISSUE THREAD

**Issue by sdc-78** [globulus/swiftui-pull-to-refresh#20]
When building a project inclusing this pod with Xcode 13.4.1, I get a `Conversion to Swift 5 is available` warning.
Since the conversion assistant tells that there is `No source changes necessary`, maybe you can increase the Swift version in the `.podspec` file ?

**Comment by gordan-glavas-codecons** [comment]
I updated this in v.1.1.7. Let me know if you still see the issue!

**Comment by sdc-78** [comment]
Great! Thanks!
